# Generated by Django 5.0.3 on 2024-03-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0004_alter_institution_member_since_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
