# Generated by Django 5.0.3 on 2024-03-06 12:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0005_delete_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_details', models.CharField(max_length=100)),
                ('official_mail', models.EmailField(max_length=200)),
                ('land_no', models.CharField(max_length=15)),
                ('pincode', models.IntegerField()),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zone', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('head_insti', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=200)),
                ('mobile_number', models.CharField(help_text='Enter your mobile number without the country code.', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='Mobile number must be 10 digits long and start with a digit between 6 and 9.', regex='^[6-9]\\d{9}$')])),
                ('member_icfoss', models.BooleanField(default=False)),
                ('member_since', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosscell.category')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosscell.universityboard')),
            ],
        ),
    ]
