# Generated by Django 5.0.3 on 2024-03-06 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0006_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='FossAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_name', models.CharField(max_length=150)),
                ('advisor_designation', models.CharField(max_length=150)),
                ('advisor_Email', models.EmailField(max_length=200)),
                ('advisor_mobile_number', models.CharField(help_text='Enter your mobile number without the country code.', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='Mobile number must be 10 digits long and start with a digit between 6 and 9.', regex='^[6-9]\\d{9}$')])),
                ('adv_member_icfoss', models.BooleanField(default=False)),
                ('adv_member_since', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
