# Generated by Django 5.0.3 on 2024-03-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0007_fossadvisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fossadvisor',
            name='adv_member_icfoss',
        ),
        migrations.RemoveField(
            model_name='fossadvisor',
            name='adv_member_since',
        ),
        migrations.AddField(
            model_name='fossadvisor',
            name='advisor_member_icfoss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fossadvisor',
            name='advisor_member_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
