# Generated by Django 5.0.3 on 2024-03-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0008_remove_fossadvisor_adv_member_icfoss_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
