# Generated by Django 5.0.3 on 2024-03-07 04:34

import django.core.validators
import fosscell.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0010_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='approval_certificate',
            field=models.FileField(upload_to='approval_certificate/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), fosscell.models.validate_file_size]),
        ),
    ]
