# Generated by Django 5.0.3 on 2024-03-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0012_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
