# Generated by Django 5.0.3 on 2024-03-09 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0013_delete_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=255, unique=True)),
                ('member_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='Enter your mobile number without the country code.', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='Mobile number must be 10 digits long and start with a digit between 6 and 9.', regex='^[6-9]\\d{9}$')])),
                ('department', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('course_end_date', models.DateField()),
            ],
        ),
    ]
