# Generated by Django 5.0.3 on 2024-03-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0014_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='uniqueid',
            field=models.CharField(max_length=255),
        ),
    ]
