# Generated by Django 5.0.3 on 2024-03-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0016_alter_members_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='uniqueid',
            field=models.CharField(max_length=255),
        ),
    ]
