# Generated by Django 5.0.3 on 2024-03-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0017_alter_members_uniqueid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FossAdvisor',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='category',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='university',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
