# Generated by Django 5.0.3 on 2024-03-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0021_fossadvisor_institutionreg_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionreg',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionreg',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
