# Generated by Django 5.0.3 on 2024-03-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0022_institutionreg_remarks_institutionreg_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionreg',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
