# Generated by Django 5.0.3 on 2024-03-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosscell', '0023_alter_institutionreg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionreg',
            name='status',
            field=models.BooleanField(blank=True, default='null', null=True),
        ),
    ]
